version: "3"

services:
  #--------------------------------------------------------------------------
  # MySQL 5.7
  #--------------------------------------------------------------------------
  mysql57:
    container_name: ${ENV}-mysql57
    build:
      context: ./services/mysql
      args:
        - MYSQL_VERSION=5.7
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TIMEZONE=${TIMEZONE}
    volumes:
      - ${PWD}/services/mysql/5.7/conf:/etc/mysql/conf.d
      - ${DATA_PATH_HOST}/mysql/5.7/data:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - 3357:3306
    # command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}